# This is a basic workflow to help you get started with Actions

name: CRAWL
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aldi
        run: echo scrapy crawl aldi
